"""add runner_tokens table

Revision ID: 28b262caec74
Revises: 1df4e876b43e
Create Date: 2026-07-22 12:22:46.056487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b262caec74'
down_revision: Union[str, Sequence[str], None] = '1df4e876b43e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runner_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requester_ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runner_tokens_issued_at'), 'runner_tokens', ['issued_at'], unique=False)
    op.create_index(op.f('ix_runner_tokens_requester_ip'), 'runner_tokens', ['requester_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runner_tokens_requester_ip'), table_name='runner_tokens')
    op.drop_index(op.f('ix_runner_tokens_issued_at'), table_name='runner_tokens')
    op.drop_table('runner_tokens')
    # ### end Alembic commands ###
